version: "3"

services:

  postgres:
    image: postgres
    command: postgres -c "max_connections=300"
    container_name: "postgres"
    env_file:
      - credenciales_postgres.env
    user: root
    ports:
      - 5000:5432
    networks:
      mynetwork:
        ipv4_address: 172.19.0.4
    volumes:
      - ./postgres-data3:/var/lib/postgresql/data
      - ./source/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
