version: "3"

services:

  postgres:
    image: postgres
    command: postgres -c "max_connections=300"
    container_name: "postgresV1.4"
    env_file:
      - credenciales_postgres.env
    user: root
    ports:
      - 5000:5432
    volumes:
      - ./postgres-data7:/var/lib/postgresql/data
      - ./source/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
