version: "3"

services:

  develop:
      build:
          context: .
          dockerfile: Jupyter.Dockerfile
      container_name: develop
      volumes:
          - ./source:/data
      ports:
          - 8888:8888
      command: /bin/sh -c "jupyter lab --ip='0.0.0.0' --port=8888 --NotebookApp.token='' --no-browser --allow-root"

      restart: on-failure

  postgres:
    image: postgres
    command: postgres -c "max_connections=300"
    container_name: "postgres"
    env_file:
      - credenciales_postgres.env
    user: root
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    ports:
      - 8084:80
    env_file:
      - credenciales_pgadmin.env
    depends_on:
      - postgres