# Generated by Django 3.2.3 on 2021-05-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                ("id_case", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "case",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Catalogue",
            fields=[
                ("id_catalogue", models.AutoField(primary_key=True, serialize=False)),
                ("id_country", models.IntegerField()),
                ("id_department", models.IntegerField()),
                ("id_municipality", models.IntegerField()),
                ("id_vereda", models.IntegerField()),
                ("id_locality", models.IntegerField()),
                ("id_gain", models.IntegerField()),
                ("id_filters", models.IntegerField()),
                ("elevation", models.IntegerField(blank=True, null=True)),
                ("coordinates", models.TextField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("chunks", models.IntegerField(blank=True, null=True)),
                ("size", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "catalogue",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CatalogueObs",
            fields=[
                (
                    "id_catalogue_obs",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "catalogue_obs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Datum",
            fields=[
                ("id_datum", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "datum",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.SmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                ("id_evidence", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "evidence",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Format",
            fields=[
                ("id_format", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "format",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Funding",
            fields=[
                ("id_funding", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "funding",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Habitat",
            fields=[
                ("id_habitat", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "habitat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Hardware",
            fields=[
                ("id_hardware", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "hardware",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HSerial",
            fields=[
                ("id_h_serial", models.AutoField(primary_key=True, serialize=False)),
                ("h_serial", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "db_table": "h_serial",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id_label", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "label",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Labeled",
            fields=[
                ("id_labeled", models.AutoField(primary_key=True, serialize=False)),
                ("begin", models.IntegerField(blank=True, null=True)),
                ("label_end", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "labeled",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                ("id_memory", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "memory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PhotoPath",
            fields=[
                ("id_photo_path", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "photo_path",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Precision",
            fields=[
                ("id_precision", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "precision",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id_project", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "project",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id_record", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("size", models.FloatField(blank=True, null=True)),
                ("sample_rate", models.IntegerField(blank=True, null=True)),
                ("chunk", models.IntegerField(blank=True, null=True)),
                ("channels", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "record",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RecordObs",
            fields=[
                ("id_record_obs", models.AutoField(primary_key=True, serialize=False)),
                (
                    "observation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "record_obs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RecordPath",
            fields=[
                ("id_record_path", models.AutoField(primary_key=True, serialize=False)),
                (
                    "record_path",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fingerprint",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "record_path",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sampling",
            fields=[
                ("id_sampling", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "sampling",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id_season", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "season",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                ("id_supply", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "supply",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id_type", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
