# Generated by Django 3.2.8 on 2021-10-30 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id_filter', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'filter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrequencyDetail',
            fields=[
                ('id_frequency_detail', models.AutoField(primary_key=True, serialize=False)),
                ('id_labeled', models.IntegerField()),
                ('beginning', models.IntegerField(blank=True, null=True)),
                ('ending', models.IntegerField(blank=True, null=True)),
                ('minimal', models.IntegerField(blank=True, null=True)),
                ('maximum', models.IntegerField(blank=True, null=True)),
                ('peak', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'frequency_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id_gain', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'apiCRUD_keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id_locality', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'locality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id_measure', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'measure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Microphone',
            fields=[
                ('id_microphone', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'microphone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id_municipality', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'municipality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PulseType',
            fields=[
                ('id_pulse_type', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pulse_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id_software', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'software',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeDetail',
            fields=[
                ('id_time_detail', models.AutoField(primary_key=True, serialize=False)),
                ('id_labeled', models.IntegerField()),
                ('beginning', models.SmallIntegerField(blank=True, null=True)),
                ('ending', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vereda',
            fields=[
                ('id_vereda', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vereda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id_voucher', models.OneToOneField(db_column='id_voucher', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apiCRUD.catalogue')),
                ('id_catalogue', models.IntegerField()),
                ('voucher', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'voucher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFunding',
            fields=[
                ('id_funding', models.IntegerField(blank=True, db_index=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical funding',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
