# Generated by Django 3.2.5 on 2021-08-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
