# Generated by Django 3.2.6 on 2021-08-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0004_historicalfunding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id_measure', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'measure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id_municipality', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'municipality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PulseType',
            fields=[
                ('id_pulse_type', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pulse_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id_software', models.SmallAutoField(primary_key=True, serialize=False)),
                ('descripton', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'software',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeDetail',
            fields=[
                ('id_time_detail', models.AutoField(primary_key=True, serialize=False)),
                ('id_labeled', models.IntegerField()),
                ('beging', models.SmallIntegerField(blank=True, null=True)),
                ('ending', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vereda',
            fields=[
                ('id_vereda', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vereda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id_voucher', models.OneToOneField(db_column='id_voucher', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apiCRUD.catalogue')),
                ('id_catalogue', models.IntegerField()),
                ('voucher', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'voucher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrequencyDetail',
            fields=[
                ('id_frequency_detail', models.AutoField(primary_key=True, serialize=False)),
                ('id_labeled', models.IntegerField()),
                ('begining', models.IntegerField(blank=True, null=True)),
                ('ending', models.IntegerField(blank=True, null=True)),
                ('minimal', models.IntegerField(blank=True, null=True)),
                ('maximun', models.IntegerField(blank=True, null=True)),
                ('peak', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id_locality', models.SmallAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
