# Generated by Django 3.2.6 on 2021-08-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0005_country_department_frequencydetail_locality_measure_municipality_pulsetype_software_timedetail_vered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencydetail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'managed': False},
        ),
    ]
