# Generated by Django 3.2.7 on 2021-09-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0008_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keys',
            options={'managed': False},
        ),
    ]
