# Generated by Django 3.2.7 on 2021-09-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0009_alter_keys_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keys',
            table='keys',
        ),
    ]
