# Generated by Django 3.2.7 on 2021-09-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0010_alter_keys_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keys',
            table='apiCRUD_keys',
        ),
    ]
