# Generated by Django 3.2.6 on 2021-09-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0011_alter_keys_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id_filter', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'filter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id_gain', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'gain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Microphone',
            fields=[
                ('id_microphone', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'microphone',
                'managed': False,
            },
        ),
    ]
