<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-09-23 21:35
=======
# Generated by Django 3.2.8 on 2021-10-08 03:24
>>>>>>> 5364bf5eb3d7a8596936082627049b296c7bf15f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0011_alter_keys_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
<<<<<<< HEAD
                ('id_filter', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
=======
                ('id_filter', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('decription', models.CharField(max_length=100)),
>>>>>>> 5364bf5eb3d7a8596936082627049b296c7bf15f
            ],
            options={
                'db_table': 'filter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gain',
            fields=[
<<<<<<< HEAD
                ('id_gain', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
=======
                ('id_gain', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
>>>>>>> 5364bf5eb3d7a8596936082627049b296c7bf15f
            ],
            options={
                'db_table': 'gain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Microphone',
            fields=[
<<<<<<< HEAD
                ('id_microphone', models.AutoField(primary_key=True, serialize=False)),
=======
                ('id_microphone', models.SmallIntegerField(primary_key=True, serialize=False)),
>>>>>>> 5364bf5eb3d7a8596936082627049b296c7bf15f
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'microphone',
                'managed': False,
            },
        ),
    ]
