# Generated by Django 3.2.9 on 2021-11-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0012_filter_gain_microphone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keys',
            table='keys',
        ),
    ]
