# Generated by Django 3.2.18 on 2023-04-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0013_alter_keys_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hserial',
            options={},
        ),
    ]
