# Generated by Django 3.2.18 on 2023-04-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCRUD', '0014_alter_hserial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hserial',
            options={'managed': False},
        ),
    ]
